language: node_js
node_js:
  - "5"
  - "4"

before_install:
  - "npm install -g mocha"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

services:
  - mongodb
  
after_script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
